# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac09e1a1849159c9fb923fb0a675ba5b763d12cb5e4e8f395efc12c1e2ced0264dc52173d35c846e6d2c7cc10af948786543c7a1ea60ae415cb97bc573df4445

test:
  secret_key_base: b88ea9497ff0b1c2329e0f187b63c0c3061e8ea5020084b6e496dbb4664d5e8597b9a78aa4a70942022dd68a2d4bd5f94e13314dbf6268c52a6da1bfdaa581bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
